[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci", "cd client && npm ci", "cd server && npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
